# Generated by Django 2.2.6 on 2019-11-14 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='isopen',
        ),
        migrations.AddField(
            model_name='survey',
            name='allowedUser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
