# Generated by Django 2.2.6 on 2019-10-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_survey_anonymous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='startDate',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='description',
            new_name='desc',
        ),
    ]
