# Generated by Django 2.2.6 on 2019-10-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191026_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ques_options',
            old_name='option_id',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='ques_options',
            old_name='q_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_id',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='user_survey',
            old_name='survey_id',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='user_survey',
            old_name='user_id',
            new_name='user',
        ),
    ]
