# Generated by Django 2.2.6 on 2019-11-23 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191114_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Row',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q_type',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='response',
            name='other_text',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='allowedUser',
        ),
        migrations.AddField(
            model_name='question',
            name='constraint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='question_image'),
        ),
        migrations.AddField(
            model_name='question',
            name='other',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='file',
            field=models.FileField(null=True, upload_to='response_files'),
        ),
        migrations.AddField(
            model_name='response',
            name='options',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='other',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Row'),
        ),
        migrations.AddField(
            model_name='response',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_survey',
            name='add_collab',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('image', models.ImageField(upload_to='option_image')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Question')),
            ],
        ),
    ]
