# Generated by Django 2.2.6 on 2019-11-06 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191027_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='options',
            name='value',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Ques_options',
        ),
    ]
