# Generated by Django 2.2.6 on 2019-11-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191123_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
